// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU1yENcmPVEiuRM6qxYFOIXEcdeykl1kQ',
    appId: '1:740725106939:web:6ac23a9ceaac4bc9cf685e',
    messagingSenderId: '740725106939',
    projectId: 'attendence-4e2b1',
    authDomain: 'attendence-4e2b1.firebaseapp.com',
    storageBucket: 'attendence-4e2b1.appspot.com',
    measurementId: 'G-L1VH046L4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEEMSkt_NU9oILHARvbkuNbN7UnfRKYY',
    appId: '1:740725106939:android:a5e75b138606bad7cf685e',
    messagingSenderId: '740725106939',
    projectId: 'attendence-4e2b1',
    storageBucket: 'attendence-4e2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDODyQ2FAki4wbMT2wDRAThW3qav8XrHYk',
    appId: '1:740725106939:ios:1a2007eb9d56a3aecf685e',
    messagingSenderId: '740725106939',
    projectId: 'attendence-4e2b1',
    storageBucket: 'attendence-4e2b1.appspot.com',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDODyQ2FAki4wbMT2wDRAThW3qav8XrHYk',
    appId: '1:740725106939:ios:1a2007eb9d56a3aecf685e',
    messagingSenderId: '740725106939',
    projectId: 'attendence-4e2b1',
    storageBucket: 'attendence-4e2b1.appspot.com',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU1yENcmPVEiuRM6qxYFOIXEcdeykl1kQ',
    appId: '1:740725106939:web:02e044b9e90665e9cf685e',
    messagingSenderId: '740725106939',
    projectId: 'attendence-4e2b1',
    authDomain: 'attendence-4e2b1.firebaseapp.com',
    storageBucket: 'attendence-4e2b1.appspot.com',
    measurementId: 'G-GWMLZD14ZM',
  );

}